---
title: まいっか検出アルゴリズム（動画ごとにチャットを時系列順に処理）
---
flowchart TD
    A[データ取得 item] --> B[経過時間 取得]
    B -- 失敗 --> C[次の item へ]
    B -- 成功 --> D{経過時間 &lt; 開始時間?}
    D -- Yes --> C
    D -- No --> E{経過時間 - 開始時間 &gt; 30秒?}
    E -- Yes --> F[まいっかカウント を 0 にリセット]
    F --> G[開始時間 を リセット]
    G --> H
    E -- No --> H{"メッセージにキーワードが含まれる?<br>まいっか / ま、いっか / ま いっか / まーいっか<br>まぁいっか / まあいっか / まあ、いっか<br>まあいいか / ま、いいか / マイッカ"}
    H -- Yes --> I{開始時間 がリセットされている?}
    I -- Yes --> J[開始時間 を 経過時間 で初期化]
    I -- No --> K
    J --> K[まいっかカウント を +1]
    K --> L{まいっかカウント = 3?}
    L -- Yes --> M{経過時間 - 開始時間 &lt;= 30秒?}
    M -- Yes --> Q["結果を出力 &amp; 集計データに追加<br>再生位置 = 開始時間 - 20秒"]
    M -- No --> O[まいっかカウント を 0 にリセット]
    O --> P[開始時間 を リセット]
    P --> C
    Q --> R[まいっかカウント を 0 にリセット]
    R --> S["開始時間 を 経過時間 + オフセット時間（20秒）で更新"]
    S --> C
    L -- No --> C
    H -- No --> C
    C --> A
